stages:
  preprocess:
    cmd: python src/data/process.py
    deps:
    - data/raw/telco_data.xlsx
    - src/data/process.py
    outs:
    - data/processed
  train:
    cmd: python src/models/train.py
    deps:
    - data/processed
    - src/models/train.py
    outs:
    - models
